name: GitHub Connection problem
description: File a connection report
title: Connection problem to GitHub servers in Iran
labels: ["github", "iran"]
assignees: ["basemax"]
body:
  - type: markdown
    attributes:
      value: |
        <div dir="rtl">
          سلام وقت بخیر،

          مدتی است که گزارش هایی مبتی بر کند شدن و مشکلات شدید شبکه سرور های CDN GitHub از دوستان و افراد ایرانی دریافت می کنم.
          با مکاتبه انجام شده برای بررسی و رفع این مشکل لطفا فرم زیر را پر کنید.
          
          توجه: برخی خروجی های خواسته شده نیاز است نرم افزار `traceroute` برای لینوکس و `tracert` برای ویندوز را در سیستم خود نصب داشته باشید.        

          لطفا مشخصات را با دقت پر کنید:
        </div>

#   - type: dropdown
#     id: browsers
#     attributes:
#       label: What browsers are you seeing the problem on?
#       multiple: true
#       options:
#         - Firefox
#         - Chrome
#         - Safari
#         - Microsoft Edge
#         - Other
  
  - type: textarea
    id: ping-github
    attributes:
      label: Ping github.com
      description: Please run `ping -c 10 github.com` and copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: markdown
    validations:
      required: true
  - type: textarea
    id: ping-avatars
    attributes:
      label: Ping avatars.githubusercontent.com
      description: Please run `ping -c 10 avatars.githubusercontent.com` and copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: markdown
    validations:
      required: true
  - type: textarea
    id: ping-raw
    attributes:
      label: Ping raw.githubusercontent.com
      description: Please run `ping -c 10 raw.githubusercontent.com` and copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: markdown
    validations:
      required: true

  - type: textarea
    id: traceroute-github
    attributes:
      label: Traceroute/Tracert github.com
      description: Please run `traceroute github.com` if you are Linux/Unix and `tracert github.com` if you are window. And copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: markdown
    validations:
      required: true
  - type: textarea
    id: traceroute-avatars
    attributes:
      label: Traceroute/Tracert avatars.githubusercontent.com
      description: Please run `traceroute avatars.githubusercontent.com` if you are Linux/Unix and `tracert avatars.githubusercontent.com` if you are window. And copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: markdown
    validations:
      required: true
  - type: textarea
    id: traceroute-raw
    attributes:
      label: Traceroute/Tracert raw.githubusercontent.com
      description: Please run `traceroute raw.githubusercontent.com` if you are Linux/Unix and `tracert raw.githubusercontent.com` if you are window. And copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: markdown
    validations:
      required: true

  - type: textarea
    id: ping-google
    attributes:
      label: Ping google.com
      description: Please run `ping -c 10 google.com` and copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: markdown
    validations:
      required: false
  - type: textarea
    id: ping-bing
    attributes:
      label: Ping bing.com
      description: Please run `ping -c 10 bing.com` and copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: markdown
    validations:
      required: false

  - type: textarea
    id: connection-data
    attributes:
      label: Connection data
      description: "Please also click on the `Test your connection (may take several seconds)` button and include those results: https://github-debug.com/"
      render: markdown
    validations:
      required: true

  - type: input
    id: isp
    attributes:
      label: ISP Name
      description: نام شرکتی که از آن اینترنت دارید
      render: markdown
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description, What happened?
      description: Also tell us, what did you experience? (In english)
      placeholder: Tell us more about your experience and what you see!
    validations:
      required: false
