name: GitHub Connection problem
description: File a connection report
title: Connection problem to GitHub servers in Iran
labels: ["github"]
assignees: ["basemax"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
  
  - type: textarea
    id: ping-github
    attributes:
      label: Ping github.com
      description: Please run `ping -c 10 github.com` and copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: markdown
    validations:
      required: true
  - type: textarea
    id: ping-avatars
    attributes:
      label: Ping avatars.githubusercontent.com
      description: Please run `ping -c 10 avatars.githubusercontent.com` and copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: markdown
    validations:
      required: true
  - type: textarea
    id: ping-raw
    attributes:
      label: Ping raw.githubusercontent.com
      description: Please run `ping -c 10 raw.githubusercontent.com` and copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: markdown
    validations:
      required: true


  - type: textarea
    id: traceroute-github
    attributes:
      label: Traceroute github.com
      description: Please run `traceroute github.com` and copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: markdown
    validations:
      required: true
  - type: textarea
    id: traceroute-avatars
    attributes:
      label: Traceroute avatars.githubusercontent.com
      description: Please run `traceroute avatars.githubusercontent.com` and copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: markdown
    validations:
      required: true
  - type: textarea
    id: traceroute-raw
    attributes:
      label: Traceroute raw.githubusercontent.com
      description: Please run `traceroute raw.githubusercontent.com` and copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: markdown
    validations:
      required: true

  - type: textarea
    id: ping-google
    attributes:
      label: Ping google.com
      description: Please run `ping -c 10 google.com` and copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: markdown
  - type: textarea
    id: ping-bing
    attributes:
      label: Ping bing.com
      description: Please run `ping -c 10 bing.com` and copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: markdown

  - type: textarea
    id: connection-data
    attributes:
      label: Connection data
      description: "Please also click on the `Test your connection (may take several seconds)` button and include those results: https://github-debug.com/"
      render: markdown
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description, What happened?
      description: Also tell us, what did you experience?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: false
